<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>InquiryWindow</RootNamespace>
    <AssemblyName>InquiryWindow</AssemblyName>
    <UseWPF>false</UseWPF>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <ClassIslandPluginSdkVersion>2.1.1</ClassIslandPluginSdkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClassIsland.PluginSdk" Version="$(ClassIslandPluginSdkVersion)">
      <ExcludeAssets>runtime; native</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Update="manifest.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
